import { TranscriptItem } from "@/components/workspace/workspace-context";

export const VISUAL_TEST_TRANSCRIPT: TranscriptItem[] = [
  { text: "Have you ever found yourself", offset: 0, duration: 2.5 },
  { text: "staring at a blank screen,", offset: 2.5, duration: 2.0 },
  { text: "wondering how to begin a massive project?", offset: 4.5, duration: 3.5 },
  { text: "This is a common problem in software engineering.", offset: 8.0, duration: 3.0 },
  { text: "The architecture seems too complex,", offset: 11.0, duration: 2.5 },
  { text: "and the requirements keep shifting.", offset: 13.5, duration: 2.5 },
  { text: "Today, we're going to explore a new methodology", offset: 16.0, duration: 3.5 },
  { text: "that breaks down these barriers.", offset: 19.5, duration: 2.5 },
  { text: "First, let's talk about the concept of 'flow'.", offset: 22.0, duration: 3.0 },
  { text: "When you are in a flow state, your productivity skyrockets.", offset: 25.0, duration: 4.5 },
  { text: "But traditional tools constantly interrupt this state.", offset: 29.5, duration: 3.5 },
  { text: "You have to switch tabs, look up documentation,", offset: 33.0, duration: 3.0 },
  { text: "and manually synchronize your context.", offset: 36.0, duration: 3.0 },
  { text: "What if the interface itself was aware", offset: 39.0, duration: 2.5 },
  { text: "of what you were trying to understand?", offset: 41.5, duration: 3.0 },
  { text: "That's exactly what TubeLens is designed to do.", offset: 44.5, duration: 4.0 },
  { text: "By marrying video content with real-time text analysis,", offset: 48.5, duration: 4.0 },
  { text: "we create an environment where reading and watching", offset: 52.5, duration: 3.5 },
  { text: "happen simultaneously.", offset: 56.0, duration: 2.0 },
  { text: "Let me show you a concrete example.", offset: 58.0, duration: 2.5 },
  { text: "Notice how the transcript panel highlights", offset: 60.5, duration: 3.0 },
  { text: "the exact moment we are discussing.", offset: 63.5, duration: 3.0 },
  { text: "If I click ahead to 1:15, the video jumps instantly.", offset: 66.5, duration: 4.0 },
  { text: "This non-linear navigation is crucial", offset: 70.5, duration: 3.0 },
  { text: "for active learning.", offset: 73.5, duration: 2.0 },
  { text: "You aren't just passively consuming video anymore.", offset: 75.5, duration: 3.5 },
  { text: "You are actively navigating an information space.", offset: 79.0, duration: 3.5 },
  { text: "Next, consider the role of the AI Companion.", offset: 82.5, duration: 3.0 },
  { text: "It sits right beside the content,", offset: 85.5, duration: 2.5 },
  { text: "ready to answer questions without breaking your context.", offset: 88.0, duration: 4.0 },
  { text: "This represents a fundamental shift in how we learn online.", offset: 92.0, duration: 4.5 },
];
